-- Migration 0003: Admin Users Table
-- Creates admin authentication system

CREATE TABLE IF NOT EXISTS admin_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- Insert initial admin user
-- Username: admin
-- Password: f8Pnf6j4KlEvnk/b (generated by setup-admin.js)
INSERT INTO admin_users (username, password_hash)
VALUES ('admin', '$2b$10$NWYw1vbkb5nmdmtfkc7E0.z6Jk0NAya0/CG1FrPMxmKGHDYxlpJP.');
